name: intellihome
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^0.8.7+3
  path_provider: ^2.0.11
  mailer: ^6.2.0
  dart_mailgun: ^1.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/images/logo.png
    - assets/users.json
